import pyfiglet 
a= pyfiglet.figlet_format("Termux-Setup") 
print(a)
print("=====================================================================")
print("apt update")
print("apt upgrade")
print("termux-setup-storage")
print("pkg install git")
print("pkg install wget")
print("pkg install python2")
print("pkg install python2")
print("pkg install python3")
print("pkg install php")
print("pkg install perl")
print("pkg install nano")
print("pkg install vim")
print("pkg install cat")
print("pkg install pip")
print("pkg install pip2")
print("pkg install pip3")
print("pip install wordlist")
print("pkg install nmap")
print("pkg install hydra")
print("pkg install openssl")
print("apt install nodejs")
